### PR TITLE
Support Kubernetes 1.30

### PR DESCRIPTION
**Pull request by ronardcaktus**
This PR updates the deployment requirements to work with Kubernetes 1.30.

### CODE REVIEW

**Comment by ronardcaktus** [comment]
According to what I found online the failure is happening due to a bug with `packaging`. The issue happens in versions less than 22, but this project has packaging version 24.2 (the latest).
Error:
```
 TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```

Discussion - https://github.com/pypa/setuptools/issues/4483

**Review by copelco — APPROVED** [review]
